version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: pg-lock-check
    main: ./cmd/pg-lock-check
    binary: pg-lock-check
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-linux-gnu
          - CXX=zig c++ -target x86_64-linux-gnu
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-gnu
          - CXX=zig c++ -target aarch64-linux-gnu
      - goos: darwin
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-macos --sysroot /opt/MacOSX14.0.sdk
          - CXX=zig c++ -target x86_64-macos --sysroot /opt/MacOSX14.0.sdk
      - goos: darwin
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-macos --sysroot /opt/MacOSX14.0.sdk
          - CXX=zig c++ -target aarch64-macos --sysroot /opt/MacOSX14.0.sdk
      - goos: windows
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-windows-gnu
          - CXX=zig c++ -target x86_64-windows-gnu
      - goos: windows
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-windows-gnu
          - CXX=zig c++ -target aarch64-windows-gnu

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: 'Features'
      regexp: '^feat'
    - title: 'Bug Fixes'
      regexp: '^fix'
    - title: 'Performance'
      regexp: '^perf'

release:
  github:
    owner: nnaka2992
    name: pg-lock-check
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## What's Changed

    **Full Changelog**: https://github.com/nnaka2992/pg-lock-check/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true