name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1
      
      - name: Set up macOS SDK for cross-compilation
        run: |
          # Download macOS SDK outside of workspace to avoid dirty git state
          pushd /tmp
          curl -L https://github.com/joseluisq/macosx-sdks/releases/download/14.0/MacOSX14.0.sdk.tar.xz -o MacOSX14.0.sdk.tar.xz
          tar -xf MacOSX14.0.sdk.tar.xz
          sudo mv MacOSX14.0.sdk /opt/
          rm MacOSX14.0.sdk.tar.xz
          popd
          echo "SDKROOT=/opt/MacOSX14.0.sdk" >> $GITHUB_ENV
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2.10.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}